### ISSUE TITLE
Implement a way of changing external reference frequency

### ISSUE THREAD

**Issue by la3pna** [etherkit/Si5351Arduino#53] opened 2017-08-31 20:55 UTC
Could we have a way to change the external reference frequency? 
Perhaps using a int32 way of changing the frequency instead of int64 to save some space?

Thomas.

**Comment by NT7S** [comment] 2017-09-09 22:47
Oops, duplicate of #25, let's use that one instead

**Closed by NT7S** 2017-09-09 22:47 UTC
Labels: enhancement
